const DominoData = [
  {
    left: 0,
    right: 0,
    sprite: 'blanks',
    frame: 2,
    inverseFrame: 2,
    isDouble: true,
  },
  {
    left: 0,
    right: 1,
    sprite: 'white_dominoes',
    frame: 0,
    inverseFrame: 1,
    isDouble: false,
  },
  {
    left: 0,
    right: 2,
    sprite: 'white_dominoes',
    frame: 8,
    inverseFrame: 9,
    isDouble: false,
  },
  {
    left: 0,
    right: 3,
    sprite: 'white_dominoes',
    frame: 16,
    inverseFrame: 17,
    isDouble: false,
  },
  {
    left: 0,
    right: 4,
    sprite: 'white_dominoes',
    frame: 24,
    inverseFrame: 25,
    isDouble: false,
  },
  {
    left: 0,
    right: 5,
    sprite: 'white_dominoes',
    frame: 32,
    inverseFrame: 33,
    isDouble: false,
  },
  {
    left: 0,
    right: 6,
    sprite: 'white_dominoes',
    frame: 40,
    inverseFrame: 41,
    isDouble: false,
  },
  {
    left: 1,
    right: 1,
    sprite: 'white_dominoes',
    frame: 2,
    inverseFrame: 2,
    isDouble: true,
  },
  {
    left: 1,
    right: 2,
    sprite: 'white_dominoes',
    frame: 3,
    inverseFrame: 10,
    isDouble: false,
  },
  {
    left: 1,
    right: 3,
    sprite: 'white_dominoes',
    frame: 4,
    inverseFrame: 18,
    isDouble: false,
  },
  {
    left: 1,
    right: 4,
    sprite: 'white_dominoes',
    frame: 5,
    inverseFrame: 26,
    isDouble: false,
  },
  {
    left: 1,
    right: 5,
    sprite: 'white_dominoes',
    frame: 6,
    inverseFrame: 34,
    isDouble: false,
  },
  {
    left: 1,
    right: 6,
    sprite: 'white_dominoes',
    frame: 7,
    inverseFrame: 42,
    isDouble: false,
  },
  {
    left: 2,
    right: 2,
    sprite: 'white_dominoes',
    frame: 11,
    inverseFrame: 11,
    isDouble: true,
  },
  {
    left: 2,
    right: 3,
    sprite: 'white_dominoes',
    frame: 12,
    inverseFrame: 19,
    isDouble: false,
  },
  {
    left: 2,
    right: 4,
    sprite: 'white_dominoes',
    frame: 13,
    inverseFrame: 27,
    isDouble: false,
  },
  {
    left: 2,
    right: 5,
    sprite: 'white_dominoes',
    frame: 14,
    inverseFrame: 35,
    isDouble: false,
  },
  {
    left: 2,
    right: 6,
    sprite: 'white_dominoes',
    frame: 15,
    inverseFrame: 43,
    isDouble: false,
  },
  {
    left: 3,
    right: 3,
    sprite: 'white_dominoes',
    frame: 20,
    inverseFrame: 20,
    isDouble: true,
  },
  {
    left: 3,
    right: 4,
    sprite: 'white_dominoes',
    frame: 21,
    inverseFrame: 28,
    isDouble: false,
  },
  {
    left: 3,
    right: 5,
    sprite: 'white_dominoes',
    frame: 22,
    inverseFrame: 35,
    isDouble: false,
  },
  {
    left: 3,
    right: 6,
    sprite: 'white_dominoes',
    frame: 23,
    inverseFrame: 44,
    isDouble: false,
  },
  {
    left: 4,
    right: 4,
    sprite: 'white_dominoes',
    frame: 29,
    inverseFrame: 29,
    isDouble: true,
  },
  {
    left: 4,
    right: 5,
    sprite: 'white_dominoes',
    frame: 30,
    inverseFrame: 37,
    isDouble: false,
  },
  {
    left: 4,
    right: 6,
    sprite: 'white_dominoes',
    frame: 31,
    inverseFrame: 45,
    isDouble: false,
  },
  {
    left: 5,
    right: 5,
    sprite: 'white_dominoes',
    frame: 38,
    inverseFrame: 38,
    isDouble: true,
  },
  {
    left: 5,
    right: 6,
    sprite: 'white_dominoes',
    frame: 39,
    inverseFrame: 46,
    isDouble: false,
  },
  {
    left: 6,
    right: 6,
    sprite: 'white_dominoes',
    frame: 47,
    inverseFrame: 47,
    isDouble: true,
  },
];

export default DominoData;
